Traceback (most recent call last):
  File "tobu.pyw", line 2309, in <module>
  File "wx\_core.pyc", line 8035, in __init__
  File "wx\_core.pyc", line 7935, in __init__
  File "wx\_core.pyc", line 7509, in _BootstrapApp
  File "tobu.pyw", line 2287, in OnInit
  File "tobu.pyw", line 231, in __init__
  File "tobu_modules\db.pyc", line 54, in __init__
pysqlite2.dbapi2.OperationalError: unable to open database file
Traceback (most recent call last):
  File "tobu.pyw", line 2309, in <module>
  File "wx\_core.pyc", line 8035, in __init__
  File "wx\_core.pyc", line 7935, in __init__
  File "wx\_core.pyc", line 7509, in _BootstrapApp
  File "tobu.pyw", line 2287, in OnInit
  File "tobu.pyw", line 231, in __init__
  File "tobu_modules\db.pyc", line 54, in __init__
pysqlite2.dbapi2.OperationalError: unable to open database file
